-- ============================================================================
-- Supabase schema snapshot – public.job_postings
-- ============================================================================
-- Purpose:
-- - Document the CURRENT live schema for public-facing job postings.
-- - Capture columns, types, nullability, defaults, and indexes as of snapshot time.
-- - Align documented schema with portal runtime expectations for job postings.
--
-- Data sources:
-- - CONFIRMED (DB): information_schema.columns / pg_indexes via Supabase tooling
--   - Tool: user-supabase.execute_sql
-- - CONFIRMED (runtime): portal job posting data + runtime modules
--   - portal/core/data/job-postings.js
--   - portal/runtime/job-offer-runtime.js
--   - portal/runtime/job-postings-list-runtime.js
--   - portal/core/data/dashboard.js (joins job_offers + job_postings)
--
-- Rules:
-- - DO NOT edit this file to change production schema.
-- - DO NOT assume this will be run automatically in production.
-- - If applied where the table already exists, IF NOT EXISTS guards make this
--   effectively an idempotent schema check; index statements align with live DB.
--
-- Column legend:
-- - [CONFIRMED_DB]: structure confirmed via information_schema.
-- - [CONFIRMED_RUNTIME]: actively used by portal runtime code.
-- - [INFERRED]: meaning inferred from naming/usage, not from constraints.
-- ============================================================================

-- High-level column summary (documentation-only)
--
-- id               uuid, PK, NOT NULL, DEFAULT gen_random_uuid()                    [CONFIRMED_DB]
-- job_offer_id     uuid, NOT NULL                                                   [CONFIRMED_DB, CONFIRMED_RUNTIME] (1:1 to job_offers.id, enforced by unique index)
-- slug             text, NOT NULL                                                   [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- public_title     text, NOT NULL                                                   [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- public_location  text, NULL                                                       [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- public_description   text, NULL                                                   [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- public_requirements  text, NULL                                                   [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- public_benefits      text, NULL                                                   [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- is_published     boolean, NOT NULL, DEFAULT false                                 [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- apply_enabled    boolean, NOT NULL, DEFAULT false                                 [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- apply_deadline   timestamptz, NULL                                                [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- published_at     timestamptz, NULL                                                [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- created_at       timestamptz, NOT NULL, DEFAULT timezone('utc', now())           [CONFIRMED_DB]
-- updated_at       timestamptz, NOT NULL, DEFAULT timezone('utc', now())           [CONFIRMED_DB]
-- created_by       uuid, NULL                                                       [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- updated_by       uuid, NULL                                                       [CONFIRMED_DB, CONFIRMED_RUNTIME]
--
-- Index summary (from pg_indexes)
-- - job_postings_pkey                         UNIQUE (id)                          [CONFIRMED_DB]
-- - job_postings_job_offer_id_unique_v1       UNIQUE (job_offer_id)                [CONFIRMED_DB]
-- - job_postings_slug_unique                  UNIQUE (slug)                        [CONFIRMED_DB]
-- - job_postings_is_published_idx             (is_published)                       [CONFIRMED_DB]
-- - job_postings_apply_deadline_idx           (apply_deadline)                     [CONFIRMED_DB]
-- - job_postings_created_at_idx               (created_at)                         [CONFIRMED_DB]
--
-- Runtime notes (portal expectations):
-- - V1 enforces a 1:1 relationship between job_offers and job_postings via
--   job_postings_job_offer_id_unique_v1.                              [CONFIRMED_RUNTIME, CONFIRMED_DB]
-- - Slug is treated as required and unique for public URLs.            [CONFIRMED_RUNTIME, CONFIRMED_DB]
-- - created_at/updated_at/created_by/updated_by are managed via
--   withInsertAuditFields / withUpdateAuditFields.                     [CONFIRMED_RUNTIME, CONFIRMED_DB]
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.job_postings (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),                  -- [CONFIRMED_DB]
  job_offer_id       uuid NOT NULL,                                               -- [CONFIRMED_DB, CONFIRMED_RUNTIME] (FK → job_offers.id, inferred)
  slug               text NOT NULL,                                               -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  public_title       text NOT NULL,                                               -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  public_location    text,                                                        -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  public_description text,                                                        -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  public_requirements text,                                                       -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  public_benefits    text,                                                        -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  is_published       boolean NOT NULL DEFAULT false,                              -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  apply_enabled      boolean NOT NULL DEFAULT false,                              -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  apply_deadline     timestamptz,                                                 -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  published_at       timestamptz,                                                 -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  created_at         timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),   -- [CONFIRMED_DB]
  updated_at         timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),   -- [CONFIRMED_DB]
  created_by         uuid,                                                        -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  updated_by         uuid                                                         -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
);

-- Indexes (idempotent definitions matching current live indexes)

CREATE UNIQUE INDEX IF NOT EXISTS job_postings_pkey
  ON public.job_postings USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS job_postings_job_offer_id_unique_v1
  ON public.job_postings USING btree (job_offer_id);

CREATE UNIQUE INDEX IF NOT EXISTS job_postings_slug_unique
  ON public.job_postings USING btree (slug);

CREATE INDEX IF NOT EXISTS job_postings_is_published_idx
  ON public.job_postings USING btree (is_published);

CREATE INDEX IF NOT EXISTS job_postings_apply_deadline_idx
  ON public.job_postings USING btree (apply_deadline);

CREATE INDEX IF NOT EXISTS job_postings_created_at_idx
  ON public.job_postings USING btree (created_at);

