-- ============================================================================
-- Supabase schema snapshot – public.external_candidate_submissions
-- ============================================================================
-- Purpose:
-- - Document the CURRENT live schema for the external submissions inbox table.
-- - Capture columns, types, nullability, defaults, and indexes as of snapshot time.
-- - This file is for documentation and verification; it should not be treated
--   as an authoritative source of truth over the live database.
--
-- Data sources:
-- - CONFIRMED (DB): information_schema.columns / pg_indexes via Supabase tooling
--   - Tool: user-supabase.execute_sql
-- - CONFIRMED (runtime): portal/features + core data/dashboard modules
--   - portal/features/external-submissions/external-submission-api.js
--   - portal/features/external-submissions/external-submissions-list.js
--   - portal/features/external-submissions/external-submission.js
--   - portal/features/external-submissions/external-submission-formatters.js
--   - portal/core/data/dashboard.js
--
-- Rules:
-- - DO NOT edit this file to change production schema.
-- - DO NOT assume this will be run automatically in production.
-- - If applied in an environment where the table already exists, the
--   IF NOT EXISTS guards mean it will act as a no-op schema check.
--
-- Column legend:
-- - [CONFIRMED_DB]: structure confirmed via information_schema.
-- - [CONFIRMED_RUNTIME]: actively used by portal runtime code.
-- - [INFERRED]: meaning inferred from naming/usage, not from constraints.
-- ============================================================================

-- High-level column summary (documentation-only)
--
-- id                         uuid, PK, NOT NULL, DEFAULT gen_random_uuid()      [CONFIRMED_DB]
-- submission_type            text, NOT NULL, DEFAULT 'spontaneous'              [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- source                     text, NOT NULL, DEFAULT 'public_form'              [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- source_page                text, NULL                                         [CONFIRMED_DB]
-- first_name                 text, NOT NULL                                     [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- last_name                  text, NOT NULL                                     [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- email                      text, NULL                                         [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- phone                      text, NULL                                         [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- address                    text, NULL                                         [CONFIRMED_DB]
-- position                   text, NULL                                         [CONFIRMED_DB]
-- linkedin_url               text, NULL                                         [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- date_of_birth              date, NULL                                         [CONFIRMED_DB]
-- summary                    text, NULL                                         [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- experience_json            jsonb, NOT NULL, DEFAULT '[]'::jsonb               [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- education_json             jsonb, NOT NULL, DEFAULT '[]'::jsonb               [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- skills_json                jsonb, NOT NULL, DEFAULT '[]'::jsonb               [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- languages_json             jsonb, NOT NULL, DEFAULT '[]'::jsonb               [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- certifications_json        jsonb, NOT NULL, DEFAULT '[]'::jsonb               [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- hobbies_json               jsonb, NOT NULL, DEFAULT '[]'::jsonb               [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- resume_path                text, NULL                                         [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- photo_path                 text, NULL                                         [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- job_offer_id               uuid, NULL                                         [CONFIRMED_DB, CONFIRMED_RUNTIME] (FK → job_offers.id, inferred)
-- linked_candidate_id        uuid, NULL                                         [CONFIRMED_DB, CONFIRMED_RUNTIME] (FK → candidates.id, inferred)
-- privacy_consent_accepted   boolean, NOT NULL, DEFAULT false                   [CONFIRMED_DB]
-- privacy_consent_at         timestamptz, NULL                                  [CONFIRMED_DB]
-- privacy_policy_version     text, NULL                                         [CONFIRMED_DB]
-- status                     text, NOT NULL, DEFAULT 'pending_review'           [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- review_notes               text, NULL                                         [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- reviewed_by                uuid, NULL                                         [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- reviewed_at                timestamptz, NULL                                  [CONFIRMED_DB, CONFIRMED_RUNTIME]
-- created_at                 timestamptz, NOT NULL, DEFAULT now()              [CONFIRMED_DB]
-- updated_at                 timestamptz, NOT NULL, DEFAULT now()              [CONFIRMED_DB]

-- Index summary (from pg_indexes)
-- - external_candidate_submissions_pkey                       UNIQUE (id)                          [CONFIRMED_DB]
-- - idx_external_candidate_submissions_created_at             (created_at DESC)                    [CONFIRMED_DB]
-- - idx_external_candidate_submissions_email                  (email)                              [CONFIRMED_DB]
-- - idx_external_candidate_submissions_job_offer_id           (job_offer_id)                       [CONFIRMED_DB]
-- - idx_external_candidate_submissions_linked_candidate_id    (linked_candidate_id)                [CONFIRMED_DB]
-- - idx_external_candidate_submissions_pending_created        (status, created_at DESC)           [CONFIRMED_DB]
-- - idx_external_candidate_submissions_phone                  (phone)                              [CONFIRMED_DB]
-- - idx_external_candidate_submissions_status                 (status)                             [CONFIRMED_DB]
-- - idx_external_candidate_submissions_submission_type        (submission_type)                    [CONFIRMED_DB]

-- ============================================================================
-- DDL snapshot (idempotent / documentation-oriented)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.external_candidate_submissions (
  id                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),         -- [CONFIRMED_DB]
  submission_type          text NOT NULL DEFAULT 'spontaneous',                -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  source                   text NOT NULL DEFAULT 'public_form',                -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  source_page              text,                                               -- [CONFIRMED_DB]
  first_name               text NOT NULL,                                      -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  last_name                text NOT NULL,                                      -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  email                    text,                                               -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  phone                    text,                                               -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  address                  text,                                               -- [CONFIRMED_DB]
  position                 text,                                               -- [CONFIRMED_DB]
  linkedin_url             text,                                               -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  date_of_birth            date,                                               -- [CONFIRMED_DB]
  summary                  text,                                               -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  experience_json          jsonb NOT NULL DEFAULT '[]'::jsonb,                 -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  education_json           jsonb NOT NULL DEFAULT '[]'::jsonb,                 -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  skills_json              jsonb NOT NULL DEFAULT '[]'::jsonb,                 -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  languages_json           jsonb NOT NULL DEFAULT '[]'::jsonb,                 -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  certifications_json      jsonb NOT NULL DEFAULT '[]'::jsonb,                 -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  hobbies_json             jsonb NOT NULL DEFAULT '[]'::jsonb,                 -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  resume_path              text,                                               -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  photo_path               text,                                               -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  job_offer_id             uuid,                                               -- [CONFIRMED_DB, CONFIRMED_RUNTIME] (FK → job_offers.id, inferred)
  linked_candidate_id      uuid,                                               -- [CONFIRMED_DB, CONFIRMED_RUNTIME] (FK → candidates.id, inferred)
  privacy_consent_accepted boolean NOT NULL DEFAULT false,                     -- [CONFIRMED_DB]
  privacy_consent_at       timestamptz,                                        -- [CONFIRMED_DB]
  privacy_policy_version   text,                                               -- [CONFIRMED_DB]
  status                   text NOT NULL DEFAULT 'pending_review',             -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  review_notes             text,                                               -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  reviewed_by              uuid,                                               -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  reviewed_at              timestamptz,                                        -- [CONFIRMED_DB, CONFIRMED_RUNTIME]
  created_at               timestamptz NOT NULL DEFAULT now(),                 -- [CONFIRMED_DB]
  updated_at               timestamptz NOT NULL DEFAULT now()                  -- [CONFIRMED_DB]
);

-- Indexes (idempotent definitions matching current live indexes)

CREATE UNIQUE INDEX IF NOT EXISTS external_candidate_submissions_pkey
  ON public.external_candidate_submissions USING btree (id);

CREATE INDEX IF NOT EXISTS idx_external_candidate_submissions_created_at
  ON public.external_candidate_submissions USING btree (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_external_candidate_submissions_email
  ON public.external_candidate_submissions USING btree (email);

CREATE INDEX IF NOT EXISTS idx_external_candidate_submissions_job_offer_id
  ON public.external_candidate_submissions USING btree (job_offer_id);

CREATE INDEX IF NOT EXISTS idx_external_candidate_submissions_linked_candidate_id
  ON public.external_candidate_submissions USING btree (linked_candidate_id);

CREATE INDEX IF NOT EXISTS idx_external_candidate_submissions_pending_created
  ON public.external_candidate_submissions USING btree (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_external_candidate_submissions_phone
  ON public.external_candidate_submissions USING btree (phone);

CREATE INDEX IF NOT EXISTS idx_external_candidate_submissions_status
  ON public.external_candidate_submissions USING btree (status);

CREATE INDEX IF NOT EXISTS idx_external_candidate_submissions_submission_type
  ON public.external_candidate_submissions USING btree (submission_type);

